version: 2.1
orbs:
  slack: circleci/slack@3.2.0

executors:
  jdk-8:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  build-jar:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run: mvn clean install

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      # Save built artifacts
      - run: mkdir artifacts && cp -r core/target/*.jar excel/target/*.jar artifacts/

      - store_artifacts:
          path: artifacts
          destination: .

      - persist_to_workspace:
          root: .
          paths:
            - core/target
            - excel/target

      - slack/status:
          success_message: JARs built successfully on $CIRCLE_BRANCH
          failure_message: Erroring building JARs on $CIRCLE_BRANCH
          webhook: https://hooks.slack.com/services/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

  build-eclipse:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - attach_workspace:
          at: .

      - run:
          command: |
            mvn install
            ./.util/build-eclipse.sh

      # Save built artifacts
      - run:
          command: |
            mkdir site
            mv plugins/eclipse/releng/update/target/repository/features site/features
            mv plugins/eclipse/releng/update/target/repository/plugins site/plugins
            mv plugins/eclipse/releng/update/target/category.xml site/site.xml

      - store_artifacts:
          path: site
          destination: .
      
      - persist_to_workspace:
          root: .
          paths:
            - site

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      
      - slack/status:
          success_message: Eclipse Update Site built successfully on $CIRCLE_BRANCH
          failure_message: Erroring building Eclipse Update Site on $CIRCLE_BRANCH
          webhook: https://hooks.slack.com/services/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

  deploy-ossrh:
    executor: jdk-8

    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - attach_workspace:
          at: .

      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes

      - run: mvn deploy -s .circleci/settings.xml -DskipTest=true

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - slack/status:
          only_for_branches: develop,master
          success_message: JARs deployed to OSSRH on $CIRCLE_BRANCH
          failure_message: Error deploying OSSRH on $CIRCLE_BRANCH
          webhook: https://hooks.slack.com/services/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

  deploy-epsilonlabs:
    executor: jdk-8
    steps:
      - attach_workspace:
          at: .

      - store_artifacts:
          path: site
          destination: .

      - run:
          name: Trigger Epsilon Labs Deployment
          command: curl -X POST "https://circleci.com/api/v1.1/project/github/epsilonlabs/epsilonlabs-updatesite?circle-token=$TRIGGER_BUILD"
      
      - slack/status:
          only_for_branches: develop,master
          success_message: Triggered EpsilonLabs deployment on $CIRCLE_BRANCH
          failure_message: Error triggering EpsilonLabs deployment on $CIRCLE_BRANCH
          webhook: https://hooks.slack.com/services/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

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-jar
      - build-eclipse:
          requires:
            - build-jar
      - deploy-ossrh:
          requires:
            - build-jar
          filters:
            branches:
              only:
                - develop
                - master
      - deploy-epsilonlabs:
          requires:
            - build-eclipse
          filters:
            branches:
              only:
                - develop
                - master
