version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      
      - run: mvn clean install -Pjacoco coveralls:report -DrepoToken=$COVERALLS_TOKEN

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Store Artifacts
      # Plugins
      - store_artifacts:
          path: ~/repo/plugins/org.apache.commons.collections_4.1.0/target/org.apache.commons.collections_4.1.0-4.1.0.jar
          destination: plugins/org.apache.commons.collections_4.1.0-4.1.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.apache.servicemix.bundles.poi_3.17.0/target/org.apache.servicemix.bundles.poi_3.17.0-3.17.0.jar
          destination: plugins/org.apache.servicemix.bundles.poi_3.17.0-3.17.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.apache.xmlbeans_2.6.0/target/org.apache.xmlbeans_2.6.0-2.6.0.jar
          destination: plugins/org.apache.xmlbeans_2.6.0-2.6.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet/target/org.eclipse.epsilon.emc.cellsheet-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.dt/target/org.eclipse.epsilon.emc.cellsheet.dt-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.dt-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel/target/org.eclipse.epsilon.emc.cellsheet.excel-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.excel-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dependencies/target/org.eclipse.epsilon.emc.cellsheet.excel.dependencies-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.excel.dependencies-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dt/target/org.eclipse.epsilon.emc.cellsheet.excel.dt-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.excel.dt-1.0.0-SNAPSHOT.jar

      # Features
      - store_artifacts:
          path: ~/repo/features/org.eclipse.epsilon.emc.cellsheet.excel.feature/target/org.eclipse.epsilon.emc.cellsheet.excel.feature-1.0.0-SNAPSHOT.jar
          destination: features/org.eclipse.epsilon.emc.cellsheet.excel.feature-1.0.0-SNAPSHOT.jar
      
      # Update Site
      - store_artifacts:
          path: ~/repo/site.xml
          destination: site.xml

  deploy-snapshot:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
      - run: echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
      - run: mvn -s .circleci/settings.xml -f standalone/pom.xml clean deploy -P ossrh -B -U -DskipTests=true

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


  deploy-labs:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    steps:
      - run: 
          name: Trigger Epsilon Labs Deployment
          command: curl -X POST "https://circleci.com/api/v1.1/project/github/epsilonlabs/epsilonlabs-updatesite?circle-token=$TRIGGER_BUILD"


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-snapshot:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /^release*/
      - deploy-labs:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /^release*/