version: 2.1
orbs:
  slack: circleci/slack@3.2.0

executors:
  jdk-8:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  "Build":
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run:
          command: |
            mvn clean test
            bash <(curl -s https://codecov.io/bash)

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - slack/status:
          success_message: JARs built successfully on $CIRCLE_BRANCH$CIRCLE_TAG
          failure_message: Erroring building JARs on $CIRCLE_BRANCH$CIRCLE_TAG

  "Deploy OSSRH":
    executor: jdk-8

    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes

      - run: mvn deploy -s .circleci/settings.xml -DskipTests -P ossrh,javadoc,sources,sign

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - slack/status:
          success_message: JARs deployed to OSSRH on $CIRCLE_BRANCH$CIRCLE_TAG
          failure_message: Error deploying OSSRH on $CIRCLE_BRANCH$CIRCLE_TAG

  "Build Eclipse":
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run:
          command: |
            mvn install -DskipTests
            ./.util/build-eclipse.sh

      # Save built artifacts
      - run:
          command: |
            mkdir site
            mv plugins/eclipse/releng/update/target/repository/features site/features
            mv plugins/eclipse/releng/update/target/repository/plugins site/plugins
            mv plugins/eclipse/releng/update/target/category.xml site/site.xml

      - store_artifacts:
          path: site
          destination: .

      - persist_to_workspace:
          root: .
          paths:
            - site

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - slack/status:
          success_message: Eclipse Update Site built successfully on $CIRCLE_BRANCH$CIRCLE_TAG
          failure_message: Erroring building Eclipse Update Site on $CIRCLE_BRANCH$CIRCLE_TAG

  "Deploy EpsilonLabs":
    executor: jdk-8
    steps:
      - attach_workspace:
          at: .

      - store_artifacts:
          path: site
          destination: .

      - run:
          name: Trigger Epsilon Labs Deployment
          command: curl -X POST "https://circleci.com/api/v1.1/project/github/epsilonlabs/epsilonlabs-updatesite?circle-token=$TRIGGER_BUILD"
      
      - slack/status:
          success_message: Triggered EpsilonLabs deployment on $CIRCLE_BRANCH$CIRCLE_TAG
          failure_message: Error triggering EpsilonLabs deployment on $CIRCLE_BRANCH$CIRCLE_TAG

workflows:
  version: 2
  branches:
    jobs:
      - "Build":
          filters:
            branches:
              ignore:
                - /release.*/
                - develop
                - master
  build-deploy:
    jobs:
      - "Build":
          filters:
            branches:
              only:
                - develop
                - /release.*/
                - master
            tags:
              only:
                - /v.*/
      - "Deploy OSSRH":
          requires:
            - "Build"
          filters:
            branches:
              only:
                - develop
                - /release.*/
                - master
            tags:
              only:
                - /v.*/