# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

      # ========================================================
      # Checkout/Build
      # ========================================================
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn clean install -Pjacoco coveralls:report -DrepoToken=$COVERALLS_TOKEN

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # ========================================================
      # Store Artifacts
      # ========================================================
      # Plugins
      - store_artifacts:
          path: ~/repo/plugins/org.apache.commons.codec_1.10/target/org.apache.commons.codec_1.10.0-1.10.0.jar
          destination: plugins/org.apache.commons.codec_1.10.0-1.10.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.apache.commons.collections_4.1.0/target/org.apache.commons.collections_4.1.0-4.1.0.jar
          destination: plugins/org.apache.commons.collections_4.1.0-4.1.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.apache.commons.logging_1.2.0/target/org.apache.commons.logging_1.2.0-1.2.0.jar
          destination: plugins/org.apache.commons.logging_1.2.0-1.2.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.apache.log4j_1.2.17/target/org.apache.log4j_1.2.17-1.2.17.jar
          destination: plugins/org.apache.log4j_1.2.17-1.2.17.jar
      - store_artifacts:
          path: ~/repo/plugins/org.apache.poi/target/org.apache.poi-3.17.0.jar
          destination: plugins/org.apache.poi-3.17.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.apache.xmlbeans_2.6.0/target/org.apache.xmlbeans_2.6.0-2.6.0.jar
          destination: plugins/org.apache.xmlbeans_2.6.0-2.6.0.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet/target/org.eclipse.epsilon.emc.cellsheet-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.dt/target/org.eclipse.epsilon.emc.cellsheet.dt-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.dt-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel/target/org.eclipse.epsilon.emc.cellsheet.excel-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.excel-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dependencies/target/org.eclipse.epsilon.emc.cellsheet.excel.dependencies-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.excel.dependencies-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dt/target/org.eclipse.epsilon.emc.cellsheet.excel.dt-1.0.0-SNAPSHOT.jar
          destination: plugins/org.eclipse.epsilon.emc.cellsheet.excel.dt-1.0.0-SNAPSHOT.jar

      # Features
      - store_artifacts:
          path: ~/repo/features/org.eclipse.epsilon.emc.cellsheet.excel.feature/target/org.eclipse.epsilon.emc.cellsheet.excel.feature-1.0.0-SNAPSHOT.jar
          destination: features/org.eclipse.epsilon.emc.cellsheet.excel.feature-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: ~/repo/features/org.eclipse.epsilon.emc.cellsheet.feature/target/org.eclipse.epsilon.emc.cellsheet.feature-1.0.0-SNAPSHOT.jar
          destination: features/org.eclipse.epsilon.emc.cellsheet.feature-1.0.0-SNAPSHOT.jar
      
      # Update Site
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.cellsheet.updatesite/site.xml
          destination: site.xml
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.cellsheet.updatesite/index.html
          destination: index.html
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.cellsheet.updatesite/web
          destination: web

      # Trigger updatesite build
      #- run: curl -X POST "https://circleci.com/api/v1.1/project/github/epsilonlabs/epsilonlabs-updatesite?circle-token=$TRIGGER_BUILD"