<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cellsheet" nsURI="org.eclipse.epsilon.emc.cellsheet" nsPrefix="cellsheet">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.eclipse.epsilon.emc"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="HasA1" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="* ===========================================================================&#xA;COMMON"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a1" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasId" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//HasId #//HasA1">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="* ===========================================================================&#xA;CORE TYPES"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sheets" upperBound="-1"
        eType="#//Sheet" containment="true" resolveProxies="false" eOpposite="#//Sheet/book"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sheet" eSuperTypes="#//HasId #//HasA1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//Row"
        containment="true" resolveProxies="false" eOpposite="#//Row/sheet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book" eOpposite="#//Book/sheets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row" eSuperTypes="#//HasId #//HasA1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true" resolveProxies="false" eOpposite="#//Cell/row"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sheet" eType="#//Sheet"
        eOpposite="#//Sheet/rows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell" eSuperTypes="#//HasId #//HasA1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a1Index" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellValue" eType="#//CellValue"
        containment="true" resolveProxies="false" eOpposite="#//CellValue/cell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sheet" eType="#//Sheet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//Row" eOpposite="#//Row/cells"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellValue" abstract="true" eSuperTypes="#//HasId">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="* ===========================================================================&#xA;CELL VALUES"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ast" eType="#//Ast" containment="true"
        resolveProxies="false" eOpposite="#//Ast/cellValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sheet" eType="#//Sheet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//Row"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" eType="#//Cell" eOpposite="#//Cell/cellValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoneCellValue" eSuperTypes="#//CellValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlankCellValue" eSuperTypes="#//CellValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringCellValue" eSuperTypes="#//CellValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormulaCellValue" eSuperTypes="#//CellValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanCellValue" eSuperTypes="#//CellValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorCellValue" eSuperTypes="#//CellValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateCellValue" eSuperTypes="#//CellValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ast" abstract="true" eSuperTypes="#//HasId">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="* ===========================================================================&#xA;AST"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Ast"
        eOpposite="#//Ast/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Ast" containment="true" resolveProxies="false" eOpposite="#//Ast/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sheet" eType="#//Sheet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//Row"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" eType="#//Cell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellValue" eType="#//CellValue"
        eOpposite="#//CellValue/ast"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="get" value="&lt;%org.eclipse.epsilon.emc.cellsheet.Ast%> _parent = this.getParent();&#xA;return (_parent == null);"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Noop" abstract="true" eSuperTypes="#//Ast"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operand" abstract="true" eSuperTypes="#//Ast"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//Ast"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorPrefix" abstract="true" eSuperTypes="#//Ast"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorInfix" abstract="true" eSuperTypes="#//Ast"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorPostfix" abstract="true" eSuperTypes="#//Ast"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unknown" abstract="true" eSuperTypes="#//Ast"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nothing" eSuperTypes="#//Unknown"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Logical" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Error" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Range" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ref" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//OperatorPrefix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Negation" eSuperTypes="#//OperatorPrefix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Percent" eSuperTypes="#//OperatorPostfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exponention" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subtraction" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Concatenation" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="EQ" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="LT" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="GT" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="LTE" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="GTE" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="NEQ" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Intersection" eSuperTypes="#//OperatorInfix"/>
  <eClassifiers xsi:type="ecore:EClass" name="Union" eSuperTypes="#//OperatorInfix"/>
</ecore:EPackage>
