# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: |
            mvn clean dependency:go-offline package

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      # - run: mvn integration-test

      # =====================
      # PROJECT SPECIFIC JARS
      # =====================
      
    - store_artifacts:
        path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dt/target/org.eclipse.epsilon.emc.cellsheet.excel.dt-1.0.0-SNAPSHOT.jar
        destination: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dt-1.0.0-SNAPSHOT.jar

    - store_artifacts:
        path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel/target/org.eclipse.epsilon.emc.cellsheet.excel-1.0.0-SNAPSHOT.jar
        destination: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel-1.0.0-SNAPSHOT.jar

    - store_artifacts:
        path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet/target/org.eclipse.epsilon.emc.cellsheet-1.0.0-SNAPSHOT.jar
        destination: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet-1.0.0-SNAPSHOT.jar

    - store_artifacts:
        path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dependencies/target/org.eclipse.epsilon.emc.cellsheet.excel.dependencies-1.0.0-SNAPSHOT.jar
        destination: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.excel.dependencies-1.0.0-SNAPSHOT.jar

    - store_artifacts:
        path: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.dt/target/org.eclipse.epsilon.emc.cellsheet.dt-1.0.0-SNAPSHOT.jar
        destination: ~/repo/plugins/org.eclipse.epsilon.emc.cellsheet.dt-1.0.0-SNAPSHOT.jar

    - store_artifacts:
        path: ~/repo/features/org.eclipse.epsilon.emc.cellsheet.feature/target/org.eclipse.epsilon.emc.cellsheet.feature-1.0.0-SNAPSHOT.jar
        destination: ~/repo/features/org.eclipse.epsilon.emc.cellsheet.feature-1.0.0-S

    - store_artifacts:
        path: ~/repo/features/org.eclipse.epsilon.emc.cellsheet.excel.feature/target/org.eclipse.epsilon.emc.cellsheet.excel.feature-1.0.0-SNAPSHOT.jar
        destination: ~/repo/features/target/org.eclipse.epsilon.emc.cellsheet.excel.feature-1.0.0-SNAPSHOT.jar

    # =========================
    # END PROJECT SPECIFIC JARS
    # =========================

    - store_artifacts:
        path: ~/repo/site.xml
        destination: site.xml

      # Trigger updatesite build    
      # - run: curl -X POST "https://circleci.com/api/v1.1/project/github/epsilonlabs/epsilonlabs-updatesite?circle-token=$TRIGGER_BUILD"